FileVersion = 1
Projects = {IDE = {Path = "."}, Beefy2D = {Path = "../BeefLibs/Beefy2D"}, IDEHelper = {Path = "../IDEHelper"}, Debugger64 = {Path = "../Debugger64"}, BeefySysLib = {Path = "../BeefySysLib"}, curl = {Path = "../BeefLibs/curl"}, libgit2 = "*"}
Unlocked = ["corlib", "libgit2"]

[Workspace]
StartupProject = "IDE"

[Configs.Debug.Win32]
InitLocalVariables = true
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
ConfigSelections = {IDEHelper = {Enabled = false}}

[Configs.Debug.Win64]
EnableSideStack = true

[Configs.Release.Win32]
BfOptimizationLevel = "OgPlus"
EmitDebugInfo = "No"
AllocStackTraceDepth = 0
ConfigSelections = {IDEHelper = {Enabled = false}}

[Configs.Release.Win64]
Toolset = "LLVM"
BfOptimizationLevel = "O3"
AllocStackTraceDepth = 0
IntermediateType = "ObjectAndIRCode"

[Configs.Debug-IDE.Win32]
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
ConfigSelections = {IDE = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug-IDE.Win64]
BfOptimizationLevel = "O0"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
ConfigSelections = {IDE = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug2.Win32]
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
ConfigSelections = {Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug2.Win64]
PreprocessorMacros = ["NEWFONT"]
IntermediateType = "ObjectAndIRCode"
ConfigSelections = {Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Paranoid.Win32]
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
EnableSideStack = false
COptimizationLevel = "O2"

[Configs.Paranoid.Win64]
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
EnableSideStack = false
COptimizationLevel = "O2"
ConfigSelections = {IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Test.Win32]
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
COptimizationLevel = "O2"

[Configs.Test.Win64]
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
COptimizationLevel = "O2"

[Configs.Debug3.Win32]
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllowHotSwapping = false
AllocStackTraceDepth = 0

[Configs.Debug3.Win64]
BfOptimizationLevel = "O0"
IntermediateType = "ObjectAndIRCode"
ConfigSelections = {Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug_NoDeps.Win32]
InitLocalVariables = true
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
ConfigSelections = {IDEHelper = {Enabled = false, Config = "Debug"}, IDE = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug_NoDeps.Win64]
EnableSideStack = true
ConfigSelections = {IDE = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, IDEHelper = {Enabled = false, Config = "Debug"}, Debugger64 = {Enabled = false, Config = "Debug"}, BeefySysLib = {Enabled = false, Config = "Debug"}}
