FileVersion = 1
Projects = {BeefBuild = {Path = "."}, corlib = "*", Beefy2D = {Path = "../BeefLibs/Beefy2D"}, IDEHelper = {Path = "../IDEHelper"}, Debugger64 = {Path = "../Debugger64"}, BeefySysLib = {Path = "../BeefySysLib"}, libgit2 = "*"}
Unlocked = ["corlib"]
ExtraPlatforms = ["Linux64"]

[Workspace]
StartupProject = "BeefBuild"

[Configs.Debug.Win32]
Toolset = "GNU"
InitLocalVariables = true
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
ConfigSelections = {IDEHelper = {Enabled = false}}

[Configs.Debug.Win64]
EnableSideStack = true
ConfigSelections = {IDEHelper = {Enabled = false}, Debugger64 = {Enabled = false}, BeefySysLib = {Enabled = false}}

[Configs.Release.Win32]
Toolset = "GNU"
BfOptimizationLevel = "OgPlus"
EmitDebugInfo = "No"
AllocStackTraceDepth = 0
ConfigSelections = {IDEHelper = {Enabled = false}}

[Configs.Release.Win64z]
EnableObjectDebugFlags = true
EmitObjectAccessCheck = true
EnableRealtimeLeakCheck = true
AllocStackTraceDepth = 0

[Configs.Debug-IDE.Win32]
Toolset = "GNU"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
ConfigSelections = {corlib = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug-IDE.Win64]
Toolset = "GNU"
BfOptimizationLevel = "O0"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
ConfigSelections = {corlib = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug2.Win32]
Toolset = "GNU"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
ConfigSelections = {corlib = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Debug2.Win64]
PreprocessorMacros = ["NEWFONT"]
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllowHotSwapping = false
IntermediateType = "ObjectAndIRCode"
ConfigSelections = {corlib = {Config = "Debug"}, Beefy2D = {Config = "Debug"}, IDEHelper = {Config = "Debug"}, Debugger64 = {Config = "Debug"}, BeefySysLib = {Config = "Debug"}}

[Configs.Paranoid.Win32]
Toolset = "GNU"
COptimizationLevel = "O2"

[Configs.Paranoid.Win64]
Toolset = "GNU"
COptimizationLevel = "O2"

[Configs.Test.Win32]
COptimizationLevel = "O2"

[Configs.Test.Win64]
COptimizationLevel = "O2"
