FileVersion = 1
Dependencies = {}

[Project]
Name = "minlib"
DefaultNamespace = ""
Aliases = ["corlib"]

[Configs.Debug.Win32]
OtherLinkFlags = ""

[[Configs.Debug.Win32.DistinctOptions]]
Filter = "[System.Optimize]"

[[Configs.Debug.Win32.DistinctOptions]]
Filter = "[System.UseLLVM]"

[Configs.Debug.Win64]
CLibType = "Static"

[[Configs.Debug.Win64.DistinctOptions]]
Filter = "[System.Optimize]"

[[Configs.Debug.Win64.DistinctOptions]]
Filter = "[System.UseLLVM]"

[Configs.Debug.WinFart]
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[[Configs.Debug.WinFart.DistinctOptions]]
Filter = "[System.UseLLVM]"

[[Configs.Debug.Linux64.DistinctOptions]]
Filter = "[System.UseLLVM]"

[[Configs.Debug.macOS.DistinctOptions]]
Filter = "[System.UseLLVM]"

[Configs.Debug.iOS]
BuildKind = "StaticLib"

[[Configs.Debug.iOS.DistinctOptions]]
Filter = "[System.UseLLVM]"

[Configs.Debug.aarch64-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[[Configs.Debug.aarch64-none-linux-android21.DistinctOptions]]
Filter = "[System.UseLLVM]"

[Configs.Release.Win32]
OtherLinkFlags = ""

[Configs.Release.Win64]
OtherLinkFlags = ""

[Configs.Release.WinFart]
OtherLinkFlags = ""

[Configs.Release.iOS]
BuildKind = "StaticLib"

[Configs.Release.aarch64-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[Configs.Test.WinFart]
BuildKind = "Normal"
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.Win32]
CLibType = "Static"

[Configs.Paranoid.Win64]
CLibType = "Static"

[Configs.Paranoid.WinFart]
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.iOS]
BuildKind = "StaticLib"

[Configs.Paranoid.aarch64-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"
