name: Build
on: [push, pull_request]
jobs:
  build-windows:
    name: Build on Windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - run: bin/build.bat
  build-linux:
    name: Build on Linux
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo apt-get update
          sudo apt-get install llvm-19-dev
      - run: bin/build.sh
  build-linux-ide:
    name: Build IDE on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install build-essential git make \
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev 
          git clone https://github.com/libsdl-org/SDL.git
          cd SDL
          mkdir build && cd build
          cmake ..
          cmake --build . --parallel
          sudo cmake --install .
        name: Build SDL3
      - uses: actions/checkout@v5
      - run: |
          sudo apt-get update
          sudo apt-get install llvm-19-dev libsystemd-dev libcurl4-openssl-dev
      - run: bin/build.sh ide
  build-macos:
    name: Build on macOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - run: |
          brew update
          brew install llvm@19
          brew link llvm@19 --force
      - run: bin/build.sh